apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configuration"
  namespace: {{ .Release.Namespace }}
  labels:
    app: worklog-police
data:
  {{- tpl (.Files.Glob "files/config.json").AsConfig . | nindent 2 }}
  {{- tpl (.Files.Glob "files/worklog-police.py").AsConfig . | nindent 2 }}